PLUGIN_ROOT         = File.expand_path(File.dirname(__FILE__) + "/..") unless defined?(PLUGIN_ROOT)
SUPPORT_TEMP        = "#{PLUGIN_ROOT}/tmp" unless defined?(SUPPORT_TEMP)
ACTIVESUPPORT_ROOT  = "#{PLUGIN_ROOT}/tmp/lib/activesupport" unless defined?(ACTIVESUPPORT_ROOT)
ACTIVERECORD_ROOT   = "#{PLUGIN_ROOT}/tmp/lib/activerecord" unless defined?(ACTIVERECORD_ROOT)
RSPEC_ROOT          = "#{PLUGIN_ROOT}/tmp/lib/rspec" unless defined?(RSPEC_ROOT)
RSPEC_ON_RAILS_ROOT = "#{PLUGIN_ROOT}/tmp/lib/rspec_on_rails" unless defined?(RSPEC_ON_RAILS_ROOT)